import { create } from 'zustand';
import type { BuilderSegmentInput, CanvasSettings, ClosureReview, DimensionLabel, FenceType, FieldChecklist, FieldChecklistKey, FieldNoteFeature, JobInfo, JogInput, LinkedLabel, LotSide, MeasureWorkspace, MeasuredEntity, MeasuredFence, MeasuredLot, MeasurementAssignmentType, MeasurementRecord, MeasuredStructure, MeasuredSurface, NorthArrow, OffsetFeatureReference, OffsetMeasurement, OffsetSession, Point, ProjectFile, ProjectFileV2, ProjectSettings, RoadMeasurement, RoadSession, SemanticLayer, SiteArcSegment, SiteBuilderSession, SiteLineSegment, SketchObject, StructureBuilderSession, StructureType, SurfaceType, Tool, Viewport, WorkspaceMode } from '../types';
import { snap, uid } from '../lib/geometry';
import { migrateProject } from '../lib/projectMigration';
import { calculateStructure, distributeStructureClosure, formatFeet, hydrateStructureCoordinates, normalizeAngle, snapStructureClosed, structureClosure } from '../lib/measurementGeometry';
import { rectangleLotGeometry, sidesFromVertices, verticesFromSides } from '../lib/lotGeometry';
import { calculateFeatureOffset, resolveFeatureLine } from '../lib/offsetGeometry';
import { calculateSitePath } from '../lib/siteGeometry';
import { defaultFieldChecklist, defaultNorthArrow, defaultProjectSettings, defaultSemanticLayers } from '../lib/projectDefaults';
import { placeDimensionLabel } from '../measurements/dimensionLayout';
import { canvasToFeet } from '../measurements/units';
import { roadGeometry } from '../lib/roadGeometry';

const today = new Date().toISOString().slice(0, 10);
const initialJob: JobInfo = { jobName:'Untitled field sketch',projectId:`ILR-${today.replaceAll('-','')}`,jobNumber:'',address:'',client:'',preparedFor:'',buyer:'',titleCompany:'',lender:'',fieldWorker:'',inspectionDate:today,notes:'',date:today };
const initialCanvas: CanvasSettings = { gridVisible: true, gridSize: 24, snapToGrid: true, measurementPrecision: 'hundredth' };
const initialViewport: Viewport = { x: 0, y: 0, scale: 1 };
type Snapshot = Pick<ProjectFileV2, 'job' | 'canvas' | 'objects' | 'layers' | 'viewport' | 'mode' | 'measuredEntities'|'lots'|'linkedLabels'|'offsets'|'fences'|'surfaces'|'roads'|'projectSettings'|'semanticLayers'|'fieldNotes'|'measurementRecords'|'dimensions'|'northArrow'|'fieldChecklist'> & {roads:RoadMeasurement[]};

interface SketchState extends Snapshot {
  projectSettings:ProjectSettings;semanticLayers:SemanticLayer[];fieldNotes:FieldNoteFeature[];measurementRecords:MeasurementRecord[];dimensions:DimensionLabel[];northArrow:NorthArrow;fieldChecklist:FieldChecklist;
  activeTool: Tool; selectedIds: string[]; past: Snapshot[]; future: Snapshot[];
  selectedMeasuredId: string | null; selectedSegmentId: string | null; closureReview: ClosureReview | null;
  measureWorkspace:MeasureWorkspace;selectedLotId:string|null;selectedLabelId:string|null;
  offsetSession:OffsetSession|null;selectedOffsetId:string|null;
  siteSession:SiteBuilderSession|null;selectedFenceId:string|null;selectedSurfaceId:string|null;
  roadSession:RoadSession|null;selectedRoadId:string|null;
  fieldNoteTool:'select'|'rough-shape'|'text'|'leader'|'measurement'|'north-arrow';fieldNoteDraft:Point[];fieldNoteText:string;
  builderSession: StructureBuilderSession | null;
  setTool: (tool: Tool) => void; setSelection: (ids: string[]) => void; addObject: (object: SketchObject) => void;
  updateObject: (id: string, patch: Partial<SketchObject>, history?: boolean) => void; updateObjects: (updates: Record<string, Partial<SketchObject>>) => void;
  deleteSelected: () => void; duplicateSelected: () => void; reorder: (direction: 'forward' | 'backward') => void;
  setJob: (patch: Partial<JobInfo>) => void; setCanvas: (patch: Partial<CanvasSettings>) => void; setViewport: (viewport: Viewport) => void;
  newProject: () => void; loadProject: (project: ProjectFile) => void; serialize: () => ProjectFile; undo: () => void; redo: () => void;
  setMode: (mode: WorkspaceMode) => void; setSelectedMeasured: (id: string | null) => void;
  addMeasuredEntity: (entity: MeasuredEntity) => void; updateMeasuredStructure: (id: string, patch: Partial<MeasuredStructure>) => void;
  deleteMeasuredEntity: (id: string) => void;
  beginStructure: (type: StructureType, name: string) => void; placeStructureStart: (point: Point) => void;
  addBuilderSegment: (input: BuilderSegmentInput) => void; undoBuilderSegment: () => void;
  finishBuilder: (closed: boolean) => void; cancelBuilder: () => void;
  setSelectedSegment: (structureId:string,segmentId:string|null) => void;
  insertSegment: (structureId:string,index:number) => void; deleteSegment:(structureId:string,segmentId:string)=>void; reverseSegment:(structureId:string,segmentId:string)=>void;
  requestClosure:(structureId:string)=>void; resolveClosure:(choice:'keep-open'|'add-wall'|'snap'|'distribute'|'return')=>void;
  setMeasureWorkspace:(workspace:MeasureWorkspace)=>void;setSelectedLot:(id:string|null)=>void;
  addRectangleLot:(data:{name:string;blockInfo?:string;width:number;depth:number;notes:string})=>void;
  addPolygonLot:(data:{name:string;blockInfo?:string;sides:LotSide[];notes:string})=>void;convertSketchObjectToLot:(objectId:string,name:string)=>void;
  updateLot:(id:string,patch:Partial<MeasuredLot>)=>void;deleteLot:(id:string)=>void;
  addLinkedLabel:(label:LinkedLabel)=>void;updateLinkedLabel:(id:string,patch:Partial<LinkedLabel>)=>void;deleteLinkedLabel:(id:string)=>void;
  beginOffset:()=>void;chooseOffsetFeature:(feature:OffsetFeatureReference)=>void;setOffsetLocation:(point:Point)=>void;cancelOffset:()=>void;
  saveOffset:(data:{measuredValue:number;label:string;labelSide:'left'|'right';orientation:'horizontal'|'vertical'|'aligned';notes:string;verified:boolean})=>void;deleteOffset:(id:string)=>void;
  beginRoad:()=>void;setRoadLocation:(point:Point)=>void;cancelRoad:()=>void;saveRoad:(data:{streetName:string;measuredWidth:number;roadAngle:number;referenceLength:number;verified:boolean;notes:string})=>void;updateRoad:(id:string,patch:Partial<RoadMeasurement>)=>void;deleteRoad:(id:string)=>void;
  addJog:(structureId:string,afterIndex:number,input:JogInput)=>void;
  beginSiteFeature:(kind:'fence'|'surface',type:FenceType|SurfaceType)=>void;placeSiteStart:(point:Point)=>void;
  addSiteLine:(segment:Omit<SiteLineSegment,'id'|'label'>)=>void;addSiteArc:(segment:Omit<SiteArcSegment,'id'|'label'>)=>void;finishSiteFeature:(closed:boolean)=>void;
  updateFence:(id:string,patch:Partial<MeasuredFence>)=>void;updateSurface:(id:string,patch:Partial<MeasuredSurface>)=>void;deleteSiteFeature:(kind:'fence'|'surface',id:string)=>void;
  setFieldNoteTool:(tool:SketchState['fieldNoteTool'])=>void;setFieldNoteText:(text:string)=>void;addFieldNotePoint:(point:Point)=>void;finishRoughNote:(closed:boolean)=>void;addTextNote:(point:Point,text:string)=>void;addLeaderNote:(start:Point,end:Point,text:string)=>void;updateFieldNote:(id:string,patch:Partial<FieldNoteFeature>)=>void;
  addMeasurementRecord:(data:{value:number;measurementText:string;note:string;featureType:string;temporaryLocation?:Point;needsVoice?:boolean})=>void;assignMeasurement:(id:string,type:MeasurementAssignmentType,objectId?:string,start?:Point,end?:Point)=>void;
  updateDimension:(id:string,patch:Partial<DimensionLabel>)=>void;updateSemanticLayer:(id:SemanticLayer['id'],patch:Partial<SemanticLayer>)=>void;reorderSemanticLayer:(id:SemanticLayer['id'],direction:-1|1)=>void;
  updateProjectSettings:(patch:Partial<ProjectSettings>)=>void;updateNorthArrow:(patch:Partial<NorthArrow>)=>void;updateChecklist:(key:FieldChecklistKey,value:boolean)=>void;
  convertRoughToStructure:(id:string)=>void;
}

// Commands record project snapshots, keeping persistence and undo/redo independent
// from React and Konva. Future object types can join the model without UI rewrites.
const snapshot = (s: SketchState): Snapshot => ({ job: structuredClone(s.job), canvas: { ...s.canvas }, objects: structuredClone(s.objects), layers: [...s.layers], viewport: { ...s.viewport }, mode: s.mode, measuredEntities: structuredClone(s.measuredEntities),lots:structuredClone(s.lots),linkedLabels:structuredClone(s.linkedLabels),offsets:structuredClone(s.offsets),fences:structuredClone(s.fences),surfaces:structuredClone(s.surfaces),roads:structuredClone(s.roads),projectSettings:structuredClone(s.projectSettings),semanticLayers:structuredClone(s.semanticLayers),fieldNotes:structuredClone(s.fieldNotes),measurementRecords:structuredClone(s.measurementRecords),dimensions:structuredClone(s.dimensions),northArrow:structuredClone(s.northArrow),fieldChecklist:structuredClone(s.fieldChecklist) });
const commit = (s: SketchState) => ({ past: [...s.past.slice(-49), snapshot(s)], future: [] });

export const useSketchStore = create<SketchState>((set, get) => ({
  job: initialJob, canvas: initialCanvas, objects: [], layers: [], viewport: initialViewport, mode: 'sketch', measuredEntities: [],lots:[],linkedLabels:[],offsets:[],fences:[],surfaces:[],roads:[],projectSettings:defaultProjectSettings(),semanticLayers:defaultSemanticLayers(),fieldNotes:[],measurementRecords:[],dimensions:[],northArrow:defaultNorthArrow(),fieldChecklist:defaultFieldChecklist(),
  activeTool: 'select', selectedIds: [], selectedMeasuredId: null, selectedSegmentId:null, closureReview:null,measureWorkspace:'structure',selectedLotId:null,selectedLabelId:null,offsetSession:null,selectedOffsetId:null,siteSession:null,selectedFenceId:null,selectedSurfaceId:null,roadSession:null,selectedRoadId:null,builderSession: null,fieldNoteTool:'select',fieldNoteDraft:[],fieldNoteText:'Field note',past: [], future: [],
  setMode: (mode) => set({ mode, selectedIds: [], selectedMeasuredId: null,selectedLotId:null,selectedLabelId:null, selectedSegmentId:null,closureReview:null,offsetSession:null,siteSession:null,roadSession:null,builderSession:null,fieldNoteDraft:[], activeTool: mode === 'measure' ? 'hand' : 'select' }),
  setSelectedMeasured: (selectedMeasuredId) => set({ selectedMeasuredId, selectedSegmentId:null, selectedIds: [] }),
  setSelectedSegment:(selectedMeasuredId,selectedSegmentId)=>set({selectedMeasuredId,selectedSegmentId,selectedIds:[]}),
  addMeasuredEntity: (entity) => set(s => ({ ...commit(s), measuredEntities: [...s.measuredEntities, entity], selectedMeasuredId: entity.id })),
  updateMeasuredStructure: (id, patch) => set(s => ({ ...commit(s), measuredEntities: s.measuredEntities.map(e => e.id === id ? hydrateStructureCoordinates({ ...e, ...patch }) : e) })),
  deleteMeasuredEntity: (id) => set(s => ({ ...commit(s), measuredEntities: s.measuredEntities.filter(e => e.id !== id), selectedMeasuredId: s.selectedMeasuredId === id ? null : s.selectedMeasuredId })),
  beginStructure: (structureType,name) => set({ mode:'measure',builderSession:{status:'choose-start',structureType,name,nextDirection:{directionMode:'absolute',angle:0}},selectedMeasuredId:null,activeTool:'select' }),
  placeStructureStart: (point) => set(s => { if(s.builderSession?.status!=='choose-start') return s; const id=uid(); const entity:MeasuredStructure={id,entityType:'structure',type:s.builderSession.structureType,name:s.builderSession.name,startPoint:point,segments:[],closed:false,stroke:'#235e4e',fill:'rgba(102, 157, 139, .16)',lineWidth:3}; return {...commit(s),measuredEntities:[...s.measuredEntities,entity],selectedMeasuredId:id,builderSession:{...s.builderSession,status:'walking',structureId:id}}; }),
  addBuilderSegment: (input) => set(s => { const session=s.builderSession;if(session?.status!=='walking'||!session.structureId)return s; const now=new Date().toISOString(); const current=session.nextDirection; return {...commit(s),builderSession:{...session,nextDirection:{directionMode:input.directionMode,angle:input.angle,turn:input.turn,turnAngle:input.turnAngle}},measuredEntities:s.measuredEntities.map(entity=>{if(entity.id!==session.structureId)return entity;const segment={id:uid(),parentObjectId:entity.id,sequence:entity.segments.length+1,length:input.length,directionMode:current.directionMode,angle:current.angle,turn:current.turn,turnAngle:current.turnAngle,label:formatFeet(input.length,s.canvas.measurementPrecision),measurementText:input.measurementText,visibleLabel:true,labelPosition:{x:0,y:0},startCoordinate:{x:0,y:0},endCoordinate:{x:0,y:0},notes:input.notes,verified:false,measurementSource:'field-entry' as const,createdAt:now,updatedAt:now};return hydrateStructureCoordinates({...entity,segments:[...entity.segments,segment]});})}; }),
  undoBuilderSegment: () => set(s=>{const session=s.builderSession,id=session?.structureId;if(!id||!session)return s;const entity=s.measuredEntities.find(e=>e.id===id),removed=entity?.segments.at(-1);return {...commit(s),builderSession:removed?{...session,nextDirection:{directionMode:removed.directionMode,angle:removed.angle,turn:removed.turn,turnAngle:removed.turnAngle}}:session,measuredEntities:s.measuredEntities.map(e=>e.id===id?hydrateStructureCoordinates({...e,segments:e.segments.slice(0,-1)}):e)}}),
  finishBuilder: (closed) => set(s=>{const id=s.builderSession?.structureId;if(!id)return {builderSession:null};return {...commit(s),closureReview:closed?{structureId:id}:null,measuredEntities:s.measuredEntities.map(e=>e.id===id?{...e,closed:false}:e),builderSession:null,selectedMeasuredId:id,activeTool:'hand'}}),
  cancelBuilder: () => set({builderSession:null,activeTool:'hand'}),
  insertSegment:(structureId,index)=>set(s=>({...commit(s),measuredEntities:s.measuredEntities.map(entity=>{if(entity.id!==structureId)return entity;const now=new Date().toISOString(),template=entity.segments[Math.max(0,Math.min(index,entity.segments.length-1))];const segment={id:uid(),parentObjectId:entity.id,sequence:index+1,length:1,directionMode:template?.directionMode??'relative' as const,angle:template?.angle,turn:template?.turn??'right' as const,turnAngle:template?.turnAngle??90,label:formatFeet(1,s.canvas.measurementPrecision),measurementText:'1',visibleLabel:true,labelPosition:{x:0,y:0},startCoordinate:{x:0,y:0},endCoordinate:{x:0,y:0},verified:false,measurementSource:'field-entry' as const,createdAt:now,updatedAt:now};const segments=[...entity.segments];segments.splice(index,0,segment);return hydrateStructureCoordinates({...entity,segments:segments.map((x,i)=>({...x,sequence:i+1}))});})})),
  deleteSegment:(structureId,segmentId)=>set(s=>({...commit(s),selectedSegmentId:s.selectedSegmentId===segmentId?null:s.selectedSegmentId,measuredEntities:s.measuredEntities.map(e=>e.id===structureId?hydrateStructureCoordinates({...e,segments:e.segments.filter(x=>x.id!==segmentId).map((x,i)=>({...x,sequence:i+1}))}):e)})),
  reverseSegment:(structureId,segmentId)=>set(s=>({...commit(s),measuredEntities:s.measuredEntities.map(e=>{if(e.id!==structureId)return e;const g=calculateStructure(e);return hydrateStructureCoordinates({...e,segments:e.segments.map((segment,index)=>segment.id===segmentId?{...segment,directionMode:'absolute',angle:normalizeAngle(g.segments[index].angle+180),turn:undefined,turnAngle:undefined,updatedAt:new Date().toISOString()}:segment)});})})),
  requestClosure:(structureId)=>set({closureReview:{structureId}}),
  resolveClosure:(choice)=>set(s=>{const review=s.closureReview;if(!review||choice==='return')return{closureReview:null};const target=s.measuredEntities.find(e=>e.id===review.structureId);if(!target)return{closureReview:null};if(choice==='keep-open')return{...commit(s),closureReview:null,measuredEntities:s.measuredEntities.map(e=>e.id===target.id?{...e,closed:false}:e)};if(choice==='snap'||choice==='distribute'){const adjusted=choice==='snap'?snapStructureClosed(target):distributeStructureClosure(target);return{...commit(s),closureReview:null,measuredEntities:s.measuredEntities.map(e=>e.id===target.id?adjusted:e)}}const closure=structureClosure(target),g=closure.geometry,start=g.points[0],end=g.points.at(-1)!,now=new Date().toISOString(),length=closure.distance,angle=normalizeAngle(Math.atan2(start.y-end.y,start.x-end.x)*180/Math.PI);const segment={id:uid(),parentObjectId:target.id,sequence:target.segments.length+1,length,directionMode:'absolute' as const,angle,label:formatFeet(length,s.canvas.measurementPrecision),measurementText:String(length),visibleLabel:true,labelPosition:{x:(start.x+end.x)/2,y:(start.y+end.y)/2},startCoordinate:end,endCoordinate:start,notes:'Measured closing wall',verified:false,measurementSource:'field-entry' as const,createdAt:now,updatedAt:now};const updated=hydrateStructureCoordinates({...target,closed:true,segments:[...target.segments,segment]});return{...commit(s),closureReview:null,measuredEntities:s.measuredEntities.map(e=>e.id===target.id?updated:e)};}),
  setMeasureWorkspace:(measureWorkspace)=>set({measureWorkspace,selectedMeasuredId:null,selectedLotId:null,selectedSegmentId:null,offsetSession:null,siteSession:null,roadSession:null}),setSelectedLot:(selectedLotId)=>set({selectedLotId,selectedMeasuredId:null,selectedSegmentId:null}),
  addRectangleLot:(data)=>set(s=>{const id=uid(),geometry=rectangleLotGeometry({x:140,y:120},data.width,data.depth);const lot:MeasuredLot={id,name:data.name,blockInfo:data.blockInfo,startPoint:{x:140,y:120},...geometry,streetAssociations:[],adjacentLotLabels:[],notes:data.notes,boundaryVisible:true,dimensionsVisible:true,stroke:'#375d8c',fill:'rgba(90,132,183,.08)',lineWidth:3};return{...commit(s),lots:[...s.lots,lot],selectedLotId:id}}),
  addPolygonLot:(data)=>set(s=>{const id=uid(),startPoint={x:140,y:120},lot:MeasuredLot={id,name:data.name,blockInfo:data.blockInfo,startPoint,sides:data.sides.map((x,i)=>({...x,sequence:i+1})),vertices:verticesFromSides(startPoint,data.sides).slice(0,-1),streetAssociations:[],adjacentLotLabels:[],notes:data.notes,boundaryVisible:true,dimensionsVisible:true,stroke:'#375d8c',fill:'rgba(90,132,183,.08)',lineWidth:3};return{...commit(s),lots:[...s.lots,lot],selectedLotId:id}}),
  convertSketchObjectToLot:(objectId,name)=>set(s=>{const object=s.objects.find(o=>o.id===objectId);if(!object)return s;const vertices=object.vertices.length?object.vertices.reduce<Point[]>((a,n,i)=>{if(i%2===0)a.push({x:object.x+n,y:object.y+object.vertices[i+1]});return a},[]):[{x:object.x,y:object.y},{x:object.x+object.width,y:object.y},{x:object.x+object.width,y:object.y+object.height},{x:object.x,y:object.y+object.height}];const id=uid(),lot:MeasuredLot={id,name,startPoint:vertices[0],vertices,sides:sidesFromVertices(vertices),streetAssociations:[],adjacentLotLabels:[],notes:`Converted from ${object.name}`,boundaryVisible:true,dimensionsVisible:true,stroke:'#375d8c',fill:'rgba(90,132,183,.08)',lineWidth:3};return{...commit(s),lots:[...s.lots,lot],objects:s.objects.filter(o=>o.id!==objectId),layers:s.layers.filter(x=>x!==objectId),selectedLotId:id}}),
  updateLot:(id,patch)=>set(s=>({...commit(s),lots:s.lots.map(lot=>lot.id===id?{...lot,...patch,...(patch.sides?{vertices:verticesFromSides(lot.startPoint,patch.sides).slice(0,-1)}:{})}:lot)})),deleteLot:(id)=>set(s=>({...commit(s),lots:s.lots.filter(l=>l.id!==id),linkedLabels:s.linkedLabels.filter(l=>l.linkedObjectId!==id),selectedLotId:null})),
  addLinkedLabel:(label)=>set(s=>({...commit(s),linkedLabels:[...s.linkedLabels,label],selectedLabelId:label.id})),updateLinkedLabel:(id,patch)=>set(s=>({...commit(s),linkedLabels:s.linkedLabels.map(l=>l.id===id?{...l,...patch}:l)})),deleteLinkedLabel:(id)=>set(s=>({...commit(s),linkedLabels:s.linkedLabels.filter(l=>l.id!==id),selectedLabelId:null})),
  beginOffset:()=>set({mode:'measure',measureWorkspace:'offset',offsetSession:{step:'first'},selectedOffsetId:null,activeTool:'select'}),
  chooseOffsetFeature:(feature)=>set(s=>{const session=s.offsetSession;if(!session)return s;if(session.step==='first')return{offsetSession:{step:'second',firstFeature:feature}};if(session.step==='second'&&session.firstFeature)return{offsetSession:{step:'location',firstFeature:session.firstFeature,secondFeature:feature}};return s}),
  setOffsetLocation:(labelAnchor)=>set(s=>s.offsetSession?.step==='location'?{offsetSession:{...s.offsetSession,step:'details',labelAnchor}}:s),cancelOffset:()=>set({offsetSession:null,activeTool:'hand'}),
  saveOffset:(data)=>set(s=>{const session=s.offsetSession;if(session?.step!=='details'||!session.firstFeature||!session.secondFeature||!session.labelAnchor)return s;const first=resolveFeatureLine(session.firstFeature,s.measuredEntities,s.lots,s.objects),second=resolveFeatureLine(session.secondFeature,s.measuredEntities,s.lots,s.objects);if(!first||!second)return s;const calculated=calculateFeatureOffset(first,second),now=new Date().toISOString(),offset:OffsetMeasurement={id:uid(),firstFeature:session.firstFeature,secondFeature:session.secondFeature,measuredValue:data.measuredValue,calculatedValue:calculated.value,label:data.label,firstAnchor:calculated.firstAnchor,secondAnchor:calculated.secondAnchor,labelAnchor:session.labelAnchor,orientation:data.orientation,labelSide:data.labelSide,leaderLines:true,extensionLines:true,verified:data.verified,notes:data.notes,createdAt:now,updatedAt:now};return{...commit(s),offsets:[...s.offsets,offset],offsetSession:null,selectedOffsetId:offset.id,activeTool:'hand'}}),deleteOffset:(id)=>set(s=>({...commit(s),offsets:s.offsets.filter(o=>o.id!==id),selectedOffsetId:null})),
  beginRoad:()=>set({mode:'measure',measureWorkspace:'road',roadSession:{step:'location'},selectedRoadId:null,activeTool:'select'}),setRoadLocation:(measurementAnchor)=>set(s=>s.roadSession?.step==='location'?{roadSession:{step:'details',measurementAnchor}}:s),cancelRoad:()=>set({roadSession:null,activeTool:'hand'}),
  saveRoad:(data)=>set(s=>{const anchor=s.roadSession?.measurementAnchor;if(!anchor)return s;const now=new Date().toISOString(),geometry=roadGeometry(anchor,data.measuredWidth,data.referenceLength,data.roadAngle,s.projectSettings.scale.feetPerCanvasUnit),id=uid(),road:RoadMeasurement={id,...data,measurementAnchor:anchor,graphicalWidth:data.measuredWidth,...geometry,createdAt:now,updatedAt:now};return{...commit(s),roads:[...s.roads,road],roadSession:null,selectedRoadId:id,activeTool:'hand'}}),updateRoad:(id,patch)=>set(s=>({...commit(s),roads:s.roads.map(road=>{if(road.id!==id)return road;const next={...road,...patch,updatedAt:new Date().toISOString()};return{...next,...roadGeometry(next.measurementAnchor,next.graphicalWidth,next.referenceLength,next.roadAngle,s.projectSettings.scale.feetPerCanvasUnit)}})})),deleteRoad:(id)=>set(s=>({...commit(s),roads:s.roads.filter(road=>road.id!==id),selectedRoadId:null})),
  addJog:(structureId,afterIndex,input)=>set(s=>({...commit(s),measuredEntities:s.measuredEntities.map(entity=>{if(entity.id!==structureId)return entity;const now=new Date().toISOString(),specs=[{length:input.firstLength,turn:input.turn},{length:input.connectingLength,turn:input.returnTurn},...(input.finalLength&&input.finalLength>0?[{length:input.finalLength,turn:input.turn}]:[])];const created=specs.map((spec,index)=>({id:uid(),parentObjectId:entity.id,sequence:afterIndex+index+1,length:spec.length,directionMode:'relative' as const,turn:spec.turn,turnAngle:90,label:formatFeet(spec.length,s.canvas.measurementPrecision),measurementText:String(spec.length),visibleLabel:true,labelPosition:{x:0,y:0},startCoordinate:{x:0,y:0},endCoordinate:{x:0,y:0},notes:'Small jog',verified:false,measurementSource:'field-entry' as const,createdAt:now,updatedAt:now}));const segments=[...entity.segments];segments.splice(afterIndex,0,...created);return hydrateStructureCoordinates({...entity,segments:segments.map((segment,index)=>({...segment,sequence:index+1}))});})})),
  beginSiteFeature:(kind,entityType)=>set({mode:'measure',measureWorkspace:kind,siteSession:{kind,status:'choose-start',entityType},activeTool:'select'}),
  placeSiteStart:(startPoint)=>set(s=>{const session=s.siteSession;if(session?.status!=='choose-start')return s;const id=uid(),name=String(session.entityType).replaceAll('-',' ').toUpperCase();if(session.kind==='fence'){const fence:MeasuredFence={id,type:session.entityType as FenceType,name,startPoint,segments:[],closed:false,gates:[],notes:'',label:`${name} FENCE`.replace(' FENCE FENCE',' FENCE'),labelVisible:true,labelPosition:{x:startPoint.x+12,y:startPoint.y-25},lineStyle:fenceStyle(session.entityType as FenceType),areaState:'open'};return{...commit(s),fences:[...s.fences,fence],selectedFenceId:id,siteSession:{...session,status:'walking',entityId:id}}}const type=session.entityType as SurfaceType,surface:MeasuredSurface={id,type,name,geometryMode:'polygon',startPoint,segments:[],vertices:[startPoint],material:type.replaceAll('-',' '),areaState:type==='covered-concrete'?'covered':'uncovered',notes:'',pattern:surfacePattern(type),label:name,labelPosition:{x:startPoint.x+12,y:startPoint.y+12}};return{...commit(s),surfaces:[...s.surfaces,surface],selectedSurfaceId:id,siteSession:{...session,status:'walking',entityId:id}}}),
  addSiteLine:(input)=>set(s=>{const session=s.siteSession;if(session?.status!=='walking'||!session.entityId)return s;const segment:SiteLineSegment={...input,id:uid(),label:formatFeet(input.length,s.canvas.measurementPrecision)};if(session.kind==='fence')return{...commit(s),fences:s.fences.map(f=>f.id===session.entityId?{...f,segments:[...f.segments,segment]}:f)};return{...commit(s),surfaces:s.surfaces.map(surface=>{if(surface.id!==session.entityId)return surface;const segments=[...surface.segments,segment];return{...surface,segments,vertices:calculateSitePath(surface.startPoint,segments).points}})} }),
  addSiteArc:(input)=>set(s=>{const session=s.siteSession;if(session?.status!=='walking'||!session.entityId)return s;const segment:SiteArcSegment={...input,id:uid(),label:input.method==='three-point'?'ARC':`R${formatFeet(input.radius??0,s.canvas.measurementPrecision)}`};if(session.kind==='fence')return{...commit(s),fences:s.fences.map(f=>f.id===session.entityId?{...f,segments:[...f.segments,segment]}:f)};return{...commit(s),surfaces:s.surfaces.map(surface=>{if(surface.id!==session.entityId)return surface;const segments=[...surface.segments,segment];return{...surface,geometryMode:'curved',segments,vertices:calculateSitePath(surface.startPoint,segments).points}})} }),
  finishSiteFeature:(closed)=>set(s=>{const session=s.siteSession;if(!session?.entityId)return{siteSession:null};return session.kind==='fence'?{...commit(s),fences:s.fences.map(f=>f.id===session.entityId?{...f,closed}:f),siteSession:null,activeTool:'hand'}:{...commit(s),surfaces:s.surfaces.map(f=>f.id===session.entityId?{...f,vertices:calculateSitePath(f.startPoint,f.segments).points}:f),siteSession:null,activeTool:'hand'}}),
  updateFence:(id,patch)=>set(s=>({...commit(s),fences:s.fences.map(f=>f.id===id?{...f,...patch}:f)})),updateSurface:(id,patch)=>set(s=>({...commit(s),surfaces:s.surfaces.map(f=>f.id===id?{...f,...patch}:f)})),deleteSiteFeature:(kind,id)=>set(s=>kind==='fence'?{...commit(s),fences:s.fences.filter(f=>f.id!==id),selectedFenceId:null}:{...commit(s),surfaces:s.surfaces.filter(f=>f.id!==id),selectedSurfaceId:null}),
  setFieldNoteTool:(fieldNoteTool)=>set({fieldNoteTool,fieldNoteDraft:[]}),setFieldNoteText:(fieldNoteText)=>set({fieldNoteText}),addFieldNotePoint:(point)=>set(s=>({fieldNoteDraft:[...s.fieldNoteDraft,point]})),
  finishRoughNote:(closed)=>set(s=>{if(s.fieldNoteDraft.length<2)return{fieldNoteDraft:[]};const note:FieldNoteFeature={id:uid(),kind:'rough-shape',name:`Rough feature ${s.fieldNotes.length+1}`,points:s.fieldNoteDraft,closed,status:'rough',layerId:'field-notes',uncertain:true,needsVerification:true,notes:''};return{...commit(s),fieldNotes:[...s.fieldNotes,note],fieldNoteDraft:[],fieldNoteTool:'select'}}),
  addTextNote:(position,textValue)=>set(s=>{const note:FieldNoteFeature={id:uid(),kind:'text',name:'Field note',position,text:textValue,status:'rough',layerId:'field-notes',uncertain:false,needsVerification:false};return{...commit(s),fieldNotes:[...s.fieldNotes,note]}}),
  addLeaderNote:(start,end,textValue)=>set(s=>{const note:FieldNoteFeature={id:uid(),kind:'leader',name:'Leader note',start,end,text:textValue,status:'rough',layerId:'field-notes',uncertain:false,needsVerification:false};return{...commit(s),fieldNotes:[...s.fieldNotes,note]}}),
  updateFieldNote:(id,patch)=>set(s=>({...commit(s),fieldNotes:s.fieldNotes.map(note=>note.id===id?({...note,...patch} as FieldNoteFeature):note)})),
  addMeasurementRecord:(data)=>set(s=>{const now=new Date().toISOString(),record:MeasurementRecord={id:uid(),value:data.value,measurementText:data.measurementText,note:data.note,featureType:data.featureType,temporaryLocation:data.temporaryLocation,voiceNotePlaceholder:data.needsVoice??false,assigned:false,createdAt:now,updatedAt:now};return{...commit(s),measurementRecords:[...s.measurementRecords,record]}}),
  assignMeasurement:(id,assignmentType,assignedObjectId,start,end)=>set(s=>{const record=s.measurementRecords.find(x=>x.id===id);if(!record)return s;const a=start??record.temporaryLocation??{x:120,y:120},b=end??{x:a.x+record.value/(s.projectSettings.scale.feetPerCanvasUnit),y:a.y},candidate={x:(a.x+b.x)/2,y:(a.y+b.y)/2-18},labelPosition=placeDimensionLabel(candidate,s.dimensions),dimension:DimensionLabel={id:uid(),measurementRecordId:id,linkedObjectId:assignedObjectId,value:record.value,text:formatFeet(record.value,s.projectSettings.displayPrecision),orientation:'aligned',start:a,end:b,labelPosition,visible:true,arrows:true,ticks:false,extensionLines:true,layerId:'dimensions'};return{...commit(s),measurementRecords:s.measurementRecords.map(x=>x.id===id?{...x,assigned:true,assignmentType,assignedObjectId,updatedAt:new Date().toISOString()}:x),dimensions:[...s.dimensions,dimension]}}),
  updateDimension:(id,patch)=>set(s=>({...commit(s),dimensions:s.dimensions.map(d=>d.id===id?{...d,...patch}:d)})),updateSemanticLayer:(id,patch)=>set(s=>({...commit(s),semanticLayers:s.semanticLayers.map(l=>l.id===id?{...l,...patch}:l)})),reorderSemanticLayer:(id,direction)=>set(s=>{const ordered=[...s.semanticLayers].sort((a,b)=>a.order-b.order),index=ordered.findIndex(x=>x.id===id),target=index+direction;if(index<0||target<0||target>=ordered.length)return s;[ordered[index],ordered[target]]=[ordered[target],ordered[index]];return{...commit(s),semanticLayers:ordered.map((l,i)=>({...l,order:i}))}}),
  updateProjectSettings:(patch)=>set(s=>({...commit(s),projectSettings:{...s.projectSettings,...patch},canvas:{...s.canvas,...(patch.displayPrecision?{measurementPrecision:patch.displayPrecision}:{}),...(patch.gridSpacingFeet?{gridSize:patch.gridSpacingFeet/s.projectSettings.scale.feetPerCanvasUnit}:{})}})),updateNorthArrow:(patch)=>set(s=>({...commit(s),northArrow:{...s.northArrow,...patch}})),updateChecklist:(key,value)=>set(s=>({...commit(s),fieldChecklist:{...s.fieldChecklist,[key]:value}})),
  convertRoughToStructure:(id)=>set(s=>{const rough=s.fieldNotes.find((x):x is Extract<FieldNoteFeature,{kind:'rough-shape'}>=>x.id===id&&x.kind==='rough-shape');if(!rough||rough.points.length<2)return s;const idNew=uid(),points=rough.closed?[...rough.points,rough.points[0]]:rough.points,now=new Date().toISOString(),segments=points.slice(0,-1).map((point,index)=>{const end=points[index+1],length=canvasToFeet(Math.hypot(end.x-point.x,end.y-point.y),s.projectSettings.scale),angle=normalizeAngle(Math.atan2(end.y-point.y,end.x-point.x)*180/Math.PI);return{id:uid(),parentObjectId:idNew,sequence:index+1,length,directionMode:'absolute' as const,angle,label:formatFeet(length,s.projectSettings.displayPrecision),measurementText:String(length),visibleLabel:true,labelPosition:{x:(point.x+end.x)/2,y:(point.y+end.y)/2},startCoordinate:point,endCoordinate:end,notes:'Converted from rough field geometry',verified:false,measurementSource:'canvas-adjustment' as const,createdAt:now,updatedAt:now}}),structure:MeasuredStructure={id:idNew,entityType:'structure',type:'other',name:rough.name,startPoint:rough.points[0],segments,closed:rough.closed,stroke:'#235e4e',fill:'rgba(102,157,139,.16)',lineWidth:3,areaState:'uncovered'};return{...commit(s),measuredEntities:[...s.measuredEntities,structure],fieldNotes:s.fieldNotes.filter(x=>x.id!==id),selectedMeasuredId:idNew,mode:'measure',measureWorkspace:'structure'}}),
  setTool: (activeTool) => set({ activeTool }), setSelection: (selectedIds) => set({ selectedIds }),
  addObject: (object) => set(s => ({ ...commit(s), objects: [...s.objects, object], layers: [...s.layers, object.id], selectedIds: [object.id], activeTool: 'select' })),
  updateObject: (id, patch, history = true) => set(s => ({ ...(history ? commit(s) : {}), objects: s.objects.map(o => o.id === id ? { ...o, ...patch } : o) })),
  updateObjects: (updates) => set(s => ({ ...commit(s), objects: s.objects.map(o => updates[o.id] ? { ...o, ...updates[o.id] } : o) })),
  deleteSelected: () => set(s => { if (s.selectedIds.length > 1 && typeof window !== 'undefined' && !window.confirm(`Delete ${s.selectedIds.length} selected objects? This can be undone.`)) return s; return { ...commit(s), objects: s.objects.filter(o => !s.selectedIds.includes(o.id)), layers: s.layers.filter(id => !s.selectedIds.includes(id)), selectedIds: [] }; }),
  duplicateSelected: () => set(s => { const copies = s.objects.filter(o => s.selectedIds.includes(o.id)).map(o => ({ ...o, id: uid(), name: `${o.name} copy`, x: snap(o.x + 24), y: snap(o.y + 24) })); return { ...commit(s), objects: [...s.objects, ...copies], layers: [...s.layers, ...copies.map(o => o.id)], selectedIds: copies.map(o => o.id) }; }),
  reorder: (direction) => set(s => { const ids = new Set(s.selectedIds); const rest = s.layers.filter(id => !ids.has(id)); const chosen = s.layers.filter(id => ids.has(id)); return { ...commit(s), layers: direction === 'forward' ? [...rest, ...chosen] : [...chosen, ...rest] }; }),
  setJob: (patch) => set(s => ({ ...commit(s), job: { ...s.job, ...patch } })), setCanvas: (patch) => set(s => ({ ...commit(s), canvas: { ...s.canvas, ...patch } })), setViewport: (viewport) => set({ viewport }),
  newProject: () => set(s => ({ ...commit(s), job: { ...initialJob, projectId: `ILR-${Date.now().toString().slice(-8)}` }, canvas: initialCanvas, objects: [], layers: [], viewport: initialViewport, mode: 'sketch', measuredEntities: [],lots:[],linkedLabels:[],offsets:[],fences:[],surfaces:[],roads:[],projectSettings:defaultProjectSettings(),semanticLayers:defaultSemanticLayers(),fieldNotes:[],measurementRecords:[],dimensions:[],northArrow:defaultNorthArrow(),fieldChecklist:defaultFieldChecklist(), selectedIds: [], selectedMeasuredId: null,selectedLotId:null,selectedLabelId:null,selectedSegmentId:null,closureReview:null,offsetSession:null,siteSession:null,roadSession:null,builderSession:null,fieldNoteDraft:[], activeTool: 'select' })),
  loadProject: (project) => set(s => { const p = migrateProject(project); return { ...commit(s), ...p, selectedIds: [], selectedMeasuredId: null,selectedSegmentId:null,closureReview:null,builderSession:null, activeTool: p.mode === 'sketch' ? 'select' : 'hand' }; }),
  serialize: () => { const s = get(); return { version: 2, schemaVersion: 2, ...snapshot(s) }; },
  undo: () => set(s => { const prev = s.past.at(-1); if (!prev) return s; return { ...prev, past: s.past.slice(0, -1), future: [snapshot(s), ...s.future], activeTool: s.activeTool, selectedIds: [] }; }),
  redo: () => set(s => { const next = s.future[0]; if (!next) return s; return { ...next, past: [...s.past, snapshot(s)], future: s.future.slice(1), activeTool: s.activeTool, selectedIds: [] }; }),
}));

function fenceStyle(type:FenceType):MeasuredFence['lineStyle']{if(type==='iron'||type==='chain-link')return'cross';if(type==='masonry-wall'||type==='stucco')return'double';if(type==='wood'||type==='privacy')return'dashed';return'solid'}
function surfacePattern(type:SurfaceType):MeasuredSurface['pattern']{if(type==='gravel')return'gravel';if(type==='asphalt')return'dots';if(type==='concrete'||type==='covered-concrete'||type==='porch-slab')return'diagonal';return'crosshatch'}
