import { X } from 'lucide-react';
import { useState } from 'react';
import { useSketchStore } from '../store/useSketchStore';
import type { JobInfo } from '../types';

export function JobModal({close}:{close:()=>void}) {
  const job=useSketchStore(s=>s.job),save=useSketchStore(s=>s.setJob),[draft,setDraft]=useState(job);
  const field=(key:keyof JobInfo)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setDraft({...draft,[key]:e.target.value});
  const submit=()=>{const inspectionDate=draft.inspectionDate??draft.date;save({...draft,inspectionDate,date:inspectionDate,projectId:draft.projectId.trim()||`ILR-${Date.now().toString().slice(-8)}`,jobName:draft.jobName.trim()||'Untitled field sketch'});close()};
  return <div className="modal-backdrop" onMouseDown={close}><div className="modal job-modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">Version 2 project details</span><h2>Job information</h2></div><button onClick={close}><X/></button></div><div className="modal-grid job-grid"><label>Job name<input autoFocus value={draft.jobName} onChange={field('jobName')} placeholder="Untitled field sketch"/></label><label>Project ID<input value={draft.projectId} onChange={field('projectId')} placeholder="Generated if blank"/></label><label>Job number<input value={draft.jobNumber??''} onChange={field('jobNumber')}/></label><label>Inspection date<input type="date" value={draft.inspectionDate??draft.date??''} onChange={field('inspectionDate')}/></label><label className="wide">Address<input value={draft.address} onChange={field('address')}/></label><label>Client<input value={draft.client} onChange={field('client')}/></label><label>Prepared for<input value={draft.preparedFor??''} onChange={field('preparedFor')}/></label><label>Buyer<input value={draft.buyer??''} onChange={field('buyer')}/></label><label>Title company<input value={draft.titleCompany??''} onChange={field('titleCompany')}/></label><label>Lender<input value={draft.lender??''} onChange={field('lender')}/></label><label>Field worker<input value={draft.fieldWorker??''} onChange={field('fieldWorker')}/></label><label className="wide">Notes<textarea rows={4} value={draft.notes} onChange={field('notes')}/></label></div><div className="modal-footer"><span className="optional-hint">Fields are optional; a project ID is generated when needed.</span><button onClick={close}>Cancel</button><button className="primary" onClick={submit}>Save job info</button></div></div></div>
}
