import { AlertTriangle, Check, Plus, Ruler, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import { formatFeet, parseFeetInput } from '../lib/measurementGeometry';
import { calculateFeatureOffset, resolveFeatureLine } from '../lib/offsetGeometry';
import { useSketchStore } from '../store/useSketchStore';

export function OffsetPanel(){const session=useSketchStore(s=>s.offsetSession),offsets=useSketchStore(s=>s.offsets),begin=useSketchStore(s=>s.beginOffset),cancel=useSketchStore(s=>s.cancelOffset),remove=useSketchStore(s=>s.deleteOffset);if(!session)return <Panel><div className="measure-intro"><div className="measure-icon"><Ruler/></div><strong>Offset measurements</strong><p>Measured offsets remain independent from scaled drawing distances.</p><button onClick={begin}><Plus size={17}/>New offset</button></div><div className="entity-list">{offsets.map(offset=><div className="offset-list-row" key={offset.id}><div><strong>{offset.label}</strong><span>{formatFeet(offset.measuredValue)}</span></div>{offset.calculatedValue!==undefined&&Math.abs(offset.calculatedValue-offset.measuredValue)>.01&&<AlertTriangle size={14}/>}<button onClick={()=>remove(offset.id)}><Trash2 size={14}/></button></div>)}</div></Panel>;if(session.step!=='details')return <Panel><div className="offset-guide"><div className="offset-stepper"><span className={session.step==='first'?'active':'done'}>1</span><i/><span className={session.step==='second'?'active':session.firstFeature?'done':''}>2</span><i/><span className={session.step==='location'?'active':''}>3</span></div><div className="target-glyph">{session.step==='location'?'✛':'⌖'}</div><strong>{session.step==='first'?'Select the first feature':session.step==='second'?'Select the second feature':'Choose measurement location'}</strong><p>{session.step==='first'?'Choose a structure wall, lot line, fence, or concrete edge.':session.step==='second'?'Choose the feature measured from the first selection.':'Tap the canvas where the offset label should appear.'}</p>{session.firstFeature&&<div className="feature-chip"><Check size={14}/>{session.firstFeature.description}</div>}{session.secondFeature&&<div className="feature-chip"><Check size={14}/>{session.secondFeature.description}</div>}<button className="cancel-offset" onClick={cancel}><X size={15}/>Cancel</button></div></Panel>;return <OffsetDetails/>}

function OffsetDetails(){const s=useSketchStore(),session=s.offsetSession!,save=s.saveOffset,cancel=s.cancelOffset;const [value,setValue]=useState(''),[label,setLabel]=useState('Offset'),[notes,setNotes]=useState(''),[side,setSide]=useState<'left'|'right'>('right'),[orientation,setOrientation]=useState<'horizontal'|'vertical'|'aligned'>('aligned'),[verified,setVerified]=useState(false),[error,setError]=useState('');const first=session.firstFeature&&resolveFeatureLine(session.firstFeature,s.measuredEntities,s.lots,s.objects),second=session.secondFeature&&resolveFeatureLine(session.secondFeature,s.measuredEntities,s.lots,s.objects),calculated=first&&second?calculateFeatureOffset(first,second).value:undefined;const parsed=parseFeetInput(value),numeric=parsed.ok?parsed.value:undefined,warning=numeric!==undefined&&calculated!==undefined&&Math.abs(numeric-calculated)>.01;const submit=()=>{const result=parseFeetInput(value);if(!result.ok){setError(result.message);return}save({measuredValue:result.value,label:label||'Offset',labelSide:side,orientation,notes,verified})};return <Panel><div className="panel-scroll"><section><span className="eyebrow">Offset details</span><h3>Enter field measurement</h3><label className="big-entry">Measured offset<div><input autoFocus inputMode="decimal" value={value} onChange={e=>{setValue(e.target.value);setError('')}} placeholder="2.25"/><span>ft</span></div></label>{error&&<div className="validation-message">{error}</div>}{calculated!==undefined&&<div className={`calculated-offset ${warning?'warning':''}`}><span>Scaled drawing distance</span><strong>{formatFeet(calculated)}</strong>{warning&&<small><AlertTriangle size={13}/>Measured and calculated values differ. Both will be saved.</small>}</div>}<label className="property-field"><span>Label</span><input value={label} onChange={e=>setLabel(e.target.value)}/></label><div className="field-row"><label className="property-field"><span>Label side</span><select value={side} onChange={e=>setSide(e.target.value as typeof side)}><option value="left">Left</option><option value="right">Right</option></select></label><label className="property-field"><span>Orientation</span><select value={orientation} onChange={e=>setOrientation(e.target.value as typeof orientation)}><option value="aligned">Aligned</option><option value="horizontal">Horizontal</option><option value="vertical">Vertical</option></select></label></div><label className="property-field"><span>Notes</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Mark field measurement verified</label><button className="begin-button" onClick={submit}>Save offset</button><button className="text-button" onClick={cancel}>Cancel</button></section></div></Panel>}
function Panel({children}:{children:React.ReactNode}){return <aside className="properties measurement-panel"><div className="panel-heading"><span>Offset Tool</span><span className="v2-pill">V2</span></div>{children}</aside>}
