import { BringToFront, Copy, Lock, SendToBack, Trash2, Unlock } from 'lucide-react';
import { useSketchStore } from '../store/useSketchStore';
import { canvasToFeet, feetToCanvas } from '../measurements/units';

const Field = ({ label, children }: { label: string; children: React.ReactNode }) => <label className="property-field"><span>{label}</span>{children}</label>;
export function PropertiesPanel() {
  const selectedIds = useSketchStore(s => s.selectedIds); const objects = useSketchStore(s => s.objects); const update = useSketchStore(s => s.updateObject);
  const remove = useSketchStore(s => s.deleteSelected); const duplicate = useSketchStore(s => s.duplicateSelected); const reorder = useSketchStore(s => s.reorder);
  const object = objects.find(o => o.id === selectedIds[0]);
  if (!object) return <aside className="properties"><div className="panel-heading"><span>Properties</span></div><div className="empty-state"><div className="empty-glyph">↖</div><strong>No object selected</strong><p>Select an object on the canvas to edit its appearance and plan dimensions.</p></div><LayersList/></aside>;
  const number = (key: 'rotation'|'lineWidth') => (e: React.ChangeEvent<HTMLInputElement>) => update(object.id, { [key]: Number(e.target.value) });
  const dimension=(key:'width'|'height')=>(e:React.ChangeEvent<HTMLInputElement>)=>{const feet=Number(e.target.value);if(Number.isFinite(feet)&&feet>=0)update(object.id,{[key]:feetToCanvas(feet,useSketchStore.getState().projectSettings.scale)})};
  const displayDimension=(value:number)=>Number(canvasToFeet(value,useSketchStore.getState().projectSettings.scale).toFixed(2));
  return <aside className="properties"><div className="panel-heading"><span>Properties</span><span className="selection-count">{selectedIds.length} selected</span></div>
    <div className="panel-scroll"><section><div className="section-label">Object</div><Field label="Name"><input value={object.name} onChange={e => update(object.id, { name: e.target.value })}/></Field><Field label="Type"><div className="readonly">{object.type}</div></Field></section>
    <section><div className="section-label">Appearance</div><div className="field-row"><Field label="Stroke"><input type="color" value={normalizeColor(object.stroke)} onChange={e => update(object.id, { stroke: e.target.value })}/></Field><Field label="Fill"><input type="color" value={normalizeColor(object.fill)} onChange={e => update(object.id, { fill: e.target.value })}/></Field></div><Field label="Line thickness"><input type="number" min="1" max="12" value={object.lineWidth} onChange={number('lineWidth')}/></Field></section>
    <section><div className="section-label">Plan dimensions</div><div className="field-row"><Field label="Width (ft)"><input type="number" inputMode="decimal" min="0" step=".01" value={displayDimension(object.width)} onChange={dimension('width')}/></Field><Field label="Depth (ft)"><input type="number" inputMode="decimal" min="0" step=".01" value={displayDimension(object.height)} onChange={dimension('height')}/></Field></div><p className="property-help">All dimensions are decimal feet in this top-down drawing. Depth does not represent physical height.</p><Field label="Rotation"><div className="input-suffix"><input type="number" value={Math.round(object.rotation)} onChange={number('rotation')}/><span>°</span></div></Field><button className="wide-action" onClick={() => update(object.id, { locked: !object.locked })}>{object.locked ? <Lock size={17}/> : <Unlock size={17}/>} {object.locked ? 'Unlock object' : 'Lock aspect ratio'}</button></section>
    <section><div className="section-label">Arrange</div><div className="arrange-grid"><button onClick={() => reorder('forward')}><BringToFront size={17}/>Bring forward</button><button onClick={() => reorder('backward')}><SendToBack size={17}/>Send backward</button><button onClick={duplicate}><Copy size={17}/>Duplicate</button><button className="delete" onClick={remove}><Trash2 size={17}/>Delete</button></div></section></div>
  </aside>;
}
const normalizeColor = (c: string) => c.startsWith('#') ? c : '#ffffff';
function LayersList(){ const objects = useSketchStore(s => s.objects); const layers = useSketchStore(s => s.layers); const select = useSketchStore(s => s.setSelection); if (!objects.length) return null; return <div className="layers"><div className="section-label">Layers · {objects.length}</div>{[...layers].reverse().map(id => { const o = objects.find(x => x.id === id); return o && <button key={id} onClick={() => select([id])}><span className={`layer-dot ${o.type}`}/><span>{o.name}</span>{o.locked && <Lock size={12}/>}</button>})}</div> }
