import { AlertTriangle, MapPinned, Plus, Trash2, X } from 'lucide-react';
import { useState } from 'react';
import { formatFeet, parseFeetInput } from '../lib/measurementGeometry';
import { useSketchStore } from '../store/useSketchStore';

export function RoadPanel(){
  const s=useSketchStore(),session=s.roadSession;
  const selected=s.roads.find(road=>road.id===s.selectedRoadId);
  if(!session&&selected)return <RoadEditor id={selected.id}/>;
  if(!session)return <Panel><div className="measure-intro"><div className="measure-icon"><MapPinned/></div><strong>Back-of-curb road measurements</strong><p>Place a measurement across the road and record the width from back of curb to back of curb. Add a second road for corner lots.</p><button onClick={s.beginRoad}><Plus size={17}/>Measure road</button></div><div className="entity-list road-list">{s.roads.map(road=><div key={road.id}><button onClick={()=>useSketchStore.setState({selectedRoadId:road.id})}><span><strong>{road.streetName}</strong><small>{formatFeet(road.measuredWidth)} back of curb</small></span></button><button aria-label={`Delete ${road.streetName}`} onClick={()=>s.deleteRoad(road.id)}><Trash2 size={15}/></button></div>)}</div></Panel>;
  if(session.step==='location')return <Panel><div className="place-start"><div className="pulse-point"/><strong>Choose the road measurement location</strong><p>Tap near the center of the road where the crew measured from back of curb to back of curb.</p><button onClick={s.cancelRoad}><X size={16}/>Cancel</button></div></Panel>;
  return <RoadDetails/>;
}

function RoadEditor({id}:{id:string}){const s=useSketchStore(),road=s.roads.find(x=>x.id===id)!;const numeric=(key:'measuredWidth'|'graphicalWidth'|'roadAngle'|'referenceLength')=>(e:React.ChangeEvent<HTMLInputElement>)=>{const value=Number(e.target.value);if(Number.isFinite(value)&&(key.includes('Width')||key==='referenceLength'?value>0:true))s.updateRoad(id,{[key]:value})};return <Panel><div className="panel-scroll"><section><div className="section-label">Road measurement</div><label className="property-field"><span>Street name</span><input value={road.streetName} onChange={e=>s.updateRoad(id,{streetName:e.target.value})}/></label><div className="field-row"><label className="property-field"><span>Measured BOC width</span><input inputMode="decimal" type="number" step=".01" value={road.measuredWidth} onChange={numeric('measuredWidth')}/></label><label className="property-field"><span>Graphical width</span><input inputMode="decimal" type="number" step=".01" value={road.graphicalWidth} onChange={numeric('graphicalWidth')}/></label></div>{Math.abs(road.measuredWidth-road.graphicalWidth)>.01&&<div className="validation-message"><AlertTriangle size={14}/>Measured and graphical widths differ. Both values are preserved.</div>}<div className="field-row"><label className="property-field"><span>Road angle</span><input type="number" value={road.roadAngle} onChange={numeric('roadAngle')}/></label><label className="property-field"><span>Visible length</span><input type="number" value={road.referenceLength} onChange={numeric('referenceLength')}/></label></div><div className="field-row"><label className="property-field"><span>Location X</span><input type="number" value={Number(road.measurementAnchor.x.toFixed(1))} onChange={e=>s.updateRoad(id,{measurementAnchor:{...road.measurementAnchor,x:Number(e.target.value)}})}/></label><label className="property-field"><span>Location Y</span><input type="number" value={Number(road.measurementAnchor.y.toFixed(1))} onChange={e=>s.updateRoad(id,{measurementAnchor:{...road.measurementAnchor,y:Number(e.target.value)}})}/></label></div><label className="property-field"><span>Notes</span><textarea rows={3} value={road.notes} onChange={e=>s.updateRoad(id,{notes:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={road.verified} onChange={e=>s.updateRoad(id,{verified:e.target.checked})}/>Measurement verified</label></section><section><button className="wide-action" onClick={()=>useSketchStore.setState({selectedRoadId:null})}>Back to roads</button><button className="delete-entity" onClick={()=>s.deleteRoad(id)}><Trash2 size={16}/>Delete road</button></section></div></Panel>}

function RoadDetails(){
  const s=useSketchStore(),[name,setName]=useState('Street'),[width,setWidth]=useState('36'),[angle,setAngle]=useState('0'),[length,setLength]=useState('80'),[notes,setNotes]=useState(''),[verified,setVerified]=useState(false),[error,setError]=useState('');
  const save=()=>{const parsed=parseFeetInput(width);if(!parsed.ok){setError(parsed.message);return}const extent=parseFeetInput(length);if(!extent.ok){setError('Enter a valid visible road length.');return}s.saveRoad({streetName:name.trim()||'Unnamed street',measuredWidth:parsed.value,roadAngle:Number(angle)||0,referenceLength:extent.value,verified,notes})};
  return <Panel><div className="panel-scroll"><section><span className="eyebrow">Road field measurement</span><h3>Back of curb to back of curb</h3><label className="property-field"><span>Street name</span><input autoFocus value={name} onChange={e=>setName(e.target.value)}/></label><label className="big-entry">Measured road width<div><input inputMode="decimal" value={width} onChange={e=>{setWidth(e.target.value);setError('')}} placeholder="36.0"/><span>ft</span></div></label>{error&&<div className="validation-message">{error}</div>}<div className="field-row"><label className="property-field"><span>Road angle</span><input inputMode="decimal" value={angle} onChange={e=>setAngle(e.target.value)}/></label><label className="property-field"><span>Visible length (ft)</span><input inputMode="decimal" value={length} onChange={e=>setLength(e.target.value)}/></label></div><p className="helper-copy">Angle controls the direction the road runs. The measured dimension is drawn perpendicular to the curbs.</p><label className="property-field"><span>Notes</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>Measurement verified</label><button className="begin-button" onClick={save}>Save road measurement</button><button className="text-button" onClick={s.cancelRoad}>Cancel</button></section></div></Panel>;
}
function Panel({children}:{children:React.ReactNode}){return <aside className="properties measurement-panel"><div className="panel-heading"><span>Road Tool</span><span className="v2-pill">Curb width</span></div>{children}</aside>}
