import Konva from 'konva';
import { forwardRef, useEffect, useImperativeHandle, useMemo, useRef, useState } from 'react';
import { Circle, Group, Layer, Line, Rect, Stage, Text, Transformer } from 'react-konva';
import { createObject, snap } from '../lib/geometry';
import { calculateStructure } from '../lib/measurementGeometry';
import { FenceShape, RoadShape, SurfaceShape } from './SiteCanvasShapes';
import { FieldNoteShapes } from './FieldNoteCanvasShapes';
import { calculateSitePath } from '../lib/siteGeometry';
import { useSketchStore } from '../store/useSketchStore';
import type { LinkedLabel, MeasuredLot, MeasuredStructure, OffsetMeasurement, ShapeType, SketchObject } from '../types';

export interface CanvasHandle { exportDataUrl: () => string; zoomToFit: () => void }
const MIN_SCALE = .25, MAX_SCALE = 3;

export const SketchCanvas = forwardRef<CanvasHandle>(function SketchCanvas(_, ref) {
  const wrap = useRef<HTMLDivElement>(null); const stageRef = useRef<Konva.Stage>(null); const transformer = useRef<Konva.Transformer>(null);
  const [size, setSize] = useState({ width: 900, height: 700 }); const [space, setSpace] = useState(false);
  const s = useSketchStore();
  useEffect(() => { if (!wrap.current) return; const ro = new ResizeObserver(([e]) => setSize({ width: e.contentRect.width, height: e.contentRect.height })); ro.observe(wrap.current); return () => ro.disconnect(); }, []);
  useEffect(()=>{const focus=(event:Event)=>{const {kind,id}=(event as CustomEvent<{kind:string;id:string}>).detail,state=useSketchStore.getState();let points:{x:number;y:number}[]=[];if(kind==='structure'){const item=state.measuredEntities.find(x=>x.id===id);if(item)points=calculateStructure(item).points}else if(kind==='lot')points=state.lots.find(x=>x.id===id)?.vertices??[];else if(kind==='fence'){const item=state.fences.find(x=>x.id===id);if(item)points=calculateSitePath(item.startPoint,item.segments).points}else if(kind==='surface'){const item=state.surfaces.find(x=>x.id===id);if(item)points=item.vertices}else if(kind==='offset'){const item=state.offsets.find(x=>x.id===id);if(item)points=[item.firstAnchor,item.secondAnchor,item.labelAnchor]}if(!points.length)return;const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y)),scale=Math.min(1.5,Math.max(.45,Math.min((size.width-140)/Math.max(80,maxX-minX),(size.height-140)/Math.max(80,maxY-minY))));state.setViewport({scale,x:size.width/2-(minX+maxX)/2*scale,y:size.height/2-(minY+maxY)/2*scale})};window.addEventListener('fieldsketch:focus',focus);return()=>window.removeEventListener('fieldsketch:focus',focus)},[size]);
  useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if (isInput(e.target)) return;
      if (e.code === 'Space') { e.preventDefault(); setSpace(true); return; }
      const state = useSketchStore.getState();
      if (e.key === 'Escape') {
        e.preventDefault();
        useSketchStore.setState({ builderSession:null, offsetSession:null, siteSession:null, roadSession:null, closureReview:null, fieldNoteDraft:[], fieldNoteTool:'select', activeTool:state.mode==='sketch'?'select':'hand' });
        return;
      }
      if (e.key === 'Delete' || e.key === 'Backspace') { e.preventDefault(); state.deleteSelected(); return; }
      if (['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key) && state.selectedIds.length) {
        e.preventDefault();
        const step=e.altKey?.1:e.shiftKey?10:1;
        const dx=e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0;
        const dy=e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0;
        const updates:Record<string,Partial<SketchObject>>={};
        state.selectedIds.forEach(id=>{const object=state.objects.find(item=>item.id===id);if(object&&!object.locked)updates[id]={x:object.x+dx,y:object.y+dy}});
        if(Object.keys(updates).length)state.updateObjects(updates);
        return;
      }
      if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'z') { e.preventDefault(); e.shiftKey ? state.redo() : state.undo(); }
    };
    const up = (e: KeyboardEvent) => e.code === 'Space' && setSpace(false);
    addEventListener('keydown', down); addEventListener('keyup', up);
    return () => { removeEventListener('keydown', down); removeEventListener('keyup', up); };
  }, []);
  useEffect(() => { const stage = stageRef.current, tr = transformer.current; if (!stage || !tr) return; tr.nodes(s.selectedIds.map(id => stage.findOne(`#${id}`)).filter(Boolean) as Konva.Node[]); tr.getLayer()?.batchDraw(); }, [s.selectedIds, s.objects]);
  useEffect(()=>{if(!s.selectedSegmentId)return;const structure=s.measuredEntities.find(e=>e.segments.some(seg=>seg.id===s.selectedSegmentId));if(!structure)return;const segment=calculateStructure(structure).segments.find(item=>item.segment.id===s.selectedSegmentId);if(!segment)return;const x=(segment.start.x+segment.end.x)/2,y=(segment.start.y+segment.end.y)/2,screenX=x*s.viewport.scale+s.viewport.x,screenY=y*s.viewport.scale+s.viewport.y,pad=90;if(screenX<pad||screenX>size.width-pad||screenY<pad||screenY>size.height-pad)s.setViewport({...s.viewport,x:size.width/2-x*s.viewport.scale,y:size.height/2-y*s.viewport.scale});},[s.selectedSegmentId]);

  const zoomToFit = () => { const bounds=s.measuredEntities.map(e=>calculateStructure(e).bounds),lotPoints=s.lots.flatMap(l=>l.vertices); const minXs=[...s.objects.map(o=>o.x),...bounds.map(b=>b.x),...lotPoints.map(p=>p.x)],minYs=[...s.objects.map(o=>o.y),...bounds.map(b=>b.y),...lotPoints.map(p=>p.y)],maxXs=[...s.objects.map(o=>o.x+o.width),...bounds.map(b=>b.x+b.width),...lotPoints.map(p=>p.x)],maxYs=[...s.objects.map(o=>o.y+o.height),...bounds.map(b=>b.y+b.height),...lotPoints.map(p=>p.y)]; if(!minXs.length){s.setViewport({x:0,y:0,scale:1});return;} const minX=Math.min(...minXs),minY=Math.min(...minYs),maxX=Math.max(...maxXs),maxY=Math.max(...maxYs); const scale=Math.min(1.5,Math.max(MIN_SCALE,Math.min((size.width-120)/Math.max(1,maxX-minX),(size.height-120)/Math.max(1,maxY-minY)))); s.setViewport({scale,x:size.width/2-(minX+maxX)/2*scale,y:size.height/2-(minY+maxY)/2*scale}); };
  useImperativeHandle(ref, () => ({ exportDataUrl: () => { const stage = stageRef.current; if (!stage) return ''; transformer.current?.hide(); const url = stage.toDataURL({ pixelRatio: 2 }); transformer.current?.show(); return url; }, zoomToFit }));

  // Objects live in stable world coordinates; only the Stage viewport pans and
  // scales. This is the basis for structured dimensions and scale math.
  const pointerWorld = () => { const p = stageRef.current?.getPointerPosition() ?? { x: 0, y: 0 }; return { x: (p.x - s.viewport.x) / s.viewport.scale, y: (p.y - s.viewport.y) / s.viewport.scale }; };
  const handleStageDown = (e: Konva.KonvaEventObject<MouseEvent | TouchEvent>) => { const empty = e.target === e.target.getStage() || e.target.name() === 'grid-bg'; if (!empty) return; const p=pointerWorld();if(s.mode==='field-note'){if(s.fieldNoteTool==='rough-shape'){s.addFieldNotePoint(p);return}if(s.fieldNoteTool==='text'){s.addTextNote(p,s.fieldNoteText);return}if(s.fieldNoteTool==='leader'){if(!s.fieldNoteDraft.length)s.addFieldNotePoint(p);else{s.addLeaderNote(s.fieldNoteDraft[0],p,s.fieldNoteText);s.setFieldNoteTool('select')}return}if(s.fieldNoteTool==='north-arrow'){s.updateNorthArrow({position:p,visible:true});return}} if(s.roadSession?.step==='location'){s.setRoadLocation(p);return;} if(s.siteSession?.status==='choose-start'){s.placeSiteStart(p);return;} if(s.offsetSession?.step==='location'){s.setOffsetLocation(p);return;} if(s.builderSession?.status==='choose-start'){s.placeStructureStart(s.canvas.snapToGrid?{x:snap(p.x,s.canvas.gridSize),y:snap(p.y,s.canvas.gridSize)}:p);return;} if (s.activeTool === 'select') s.setSelection([]); else if (s.activeTool !== 'hand') s.addObject(createObject(s.activeTool as ShapeType, p, s.objects.filter(o => o.type === s.activeTool).length + 1)); };
  const wheel = (e: Konva.KonvaEventObject<WheelEvent>) => { e.evt.preventDefault(); const p = stageRef.current?.getPointerPosition(); if (!p) return; const old = s.viewport.scale; const next = Math.max(MIN_SCALE, Math.min(MAX_SCALE, e.evt.deltaY > 0 ? old / 1.08 : old * 1.08)); const world = { x: (p.x - s.viewport.x) / old, y: (p.y - s.viewport.y) / old }; s.setViewport({ scale: next, x: p.x - world.x * next, y: p.y - world.y * next }); };
  const panning = (s.activeTool === 'hand' || space) && s.builderSession?.status !== 'choose-start';
  const ordered = useMemo(() => s.layers.map(id => s.objects.find(o => o.id === id)).filter(Boolean) as SketchObject[], [s.layers, s.objects]);
  const grid = useMemo(() => { const lines = []; const step = s.canvas.gridSize; const left = -s.viewport.x / s.viewport.scale - step, top = -s.viewport.y / s.viewport.scale - step; const right = left + size.width / s.viewport.scale + step * 2, bottom = top + size.height / s.viewport.scale + step * 2; for (let x = Math.floor(left / step) * step; x < right; x += step) lines.push(<Line key={`x${x}`} points={[x, top, x, bottom]} stroke={x % (step * 5) === 0 ? '#ccd5ce' : '#e5e9e5'} strokeWidth={(x % (step * 5) === 0 ? 1.2 : .7) / s.viewport.scale}/>); for (let y = Math.floor(top / step) * step; y < bottom; y += step) lines.push(<Line key={`y${y}`} points={[left, y, right, y]} stroke={y % (step * 5) === 0 ? '#ccd5ce' : '#e5e9e5'} strokeWidth={(y % (step * 5) === 0 ? 1.2 : .7) / s.viewport.scale}/>); return lines; }, [s.canvas, s.viewport, size]);

  return <div className={`canvas-wrap ${panning ? 'is-panning' : ''} ${s.builderSession?.status==='choose-start'?'choose-start':''}`} ref={wrap}>
    <Stage ref={stageRef} width={size.width} height={size.height} x={s.viewport.x} y={s.viewport.y} scaleX={s.viewport.scale} scaleY={s.viewport.scale} draggable={panning} onDragEnd={e => { if (e.target === stageRef.current) s.setViewport({ ...s.viewport, x: e.target.x(), y: e.target.y() }); }} onMouseDown={handleStageDown} onTouchStart={handleStageDown} onWheel={wheel}>
      <Layer listening={false}><Rect name="grid-bg" x={-s.viewport.x/s.viewport.scale} y={-s.viewport.y/s.viewport.scale} width={size.width/s.viewport.scale} height={size.height/s.viewport.scale} fill="#f8faf7"/>{s.canvas.gridVisible && grid}</Layer>
      <Layer>{s.semanticLayers.find(x=>x.id==='surfaces')?.visible!==false&&s.surfaces.map(surface=><SurfaceShape key={surface.id} surface={surface}/>)}{s.semanticLayers.find(x=>x.id==='property')?.visible!==false&&s.lots.map(lot=><LotShape key={lot.id} lot={lot}/>)}{s.roads.map(road=><RoadShape key={road.id} road={road}/>)}{s.semanticLayers.find(x=>x.id==='structures')?.visible!==false&&s.measuredEntities.map(entity => <MeasuredStructureShape key={entity.id} structure={entity}/>)}{s.semanticLayers.find(x=>x.id==='fences')?.visible!==false&&s.fences.map(fence=><FenceShape key={fence.id} fence={fence}/>)}{s.semanticLayers.find(x=>x.id==='dimensions')?.visible!==false&&s.offsets.map(offset=><OffsetShape key={offset.id} offset={offset}/>)}{s.semanticLayers.find(x=>x.id==='labels')?.visible!==false&&s.linkedLabels.map(label=><LinkedCanvasLabel key={label.id} label={label}/>)}<FieldNoteShapes viewportScale={s.viewport.scale}/>{s.semanticLayers.find(x=>x.id==='field-notes')?.visible!==false&&s.fieldNoteDraft.length>0&&<Line points={s.fieldNoteDraft.flatMap(p=>[p.x,p.y])} stroke="#b16b2f" strokeWidth={2} dash={[7,5]}/>} {ordered.map(o => <CanvasObject key={o.id} object={o}/>) }<Transformer ref={transformer} rotateEnabled enabledAnchors={['top-left','top-right','bottom-left','bottom-right','middle-left','middle-right','top-center','bottom-center']} borderStroke="#2f6f5f" anchorStroke="#2f6f5f" anchorFill="#fff" anchorSize={10/s.viewport.scale} rotateAnchorOffset={28/s.viewport.scale} keepRatio={selectedIdsLocked(s.objects, s.selectedIds)}/></Layer>
    </Stage>
    <div className="canvas-hint"><span>{Math.round(s.viewport.scale * 100)}%</span><span>Grid {s.canvas.gridVisible ? 'on' : 'off'} · {s.canvas.gridSize}px</span></div>
  </div>;
});

function LotShape({lot}:{lot:MeasuredLot}){const selected=useSketchStore(s=>s.selectedLotId===lot.id),select=useSketchStore(s=>s.setSelectedLot),offsetSession=useSketchStore(s=>s.offsetSession),choose=useSketchStore(s=>s.chooseOffsetFeature);const closed=[...lot.vertices,lot.vertices[0]],points=closed.flatMap(p=>[p.x,p.y]);return <Group onClick={e=>{e.cancelBubble=true;select(lot.id)}}>{lot.boundaryVisible&&<Line points={points} closed fill={lot.fill} stroke={selected?'#e58b2f':lot.stroke} strokeWidth={selected?5:lot.lineWidth} lineJoin="round"/>}{lot.sides.map((side,index)=>{const start=closed[index],end=closed[index+1];return <Group key={side.id} onClick={e=>{if(offsetSession?.step==='first'||offsetSession?.step==='second'){e.cancelBubble=true;choose({kind:'lot-side',objectId:lot.id,segmentId:side.id,description:`${lot.name} side ${side.sequence}`})}}}><Line points={[start.x,start.y,end.x,end.y]} stroke="rgba(0,0,0,0)" strokeWidth={18}/>{lot.dimensionsVisible&&side.visible&&<Text x={(start.x+end.x)/2-30} y={(start.y+end.y)/2-20} width={60} text={side.label} align="center" fontSize={12} fontStyle="bold" fill="#294d77" listening={false}/>}</Group>})}<Text x={lot.startPoint.x+12} y={lot.startPoint.y+12} text={lot.name} fontSize={15} fontStyle="bold" fill="#294d77" listening={false}/></Group>}

function OffsetShape({offset}:{offset:OffsetMeasurement}){const mismatch=offset.calculatedValue!==undefined&&Math.abs(offset.calculatedValue-offset.measuredValue)>.01;return <Group><Line points={[offset.firstAnchor.x,offset.firstAnchor.y,offset.secondAnchor.x,offset.secondAnchor.y]} stroke={mismatch?'#c56b28':'#654b92'} strokeWidth={2} dash={[5,4]}/>{offset.leaderLines&&<><Line points={[offset.firstAnchor.x,offset.firstAnchor.y,offset.labelAnchor.x,offset.labelAnchor.y]} stroke="#7b6b95" strokeWidth={1}/><Line points={[offset.secondAnchor.x,offset.secondAnchor.y,offset.labelAnchor.x,offset.labelAnchor.y]} stroke="#7b6b95" strokeWidth={1}/></>}<Text x={offset.labelAnchor.x-35} y={offset.labelAnchor.y-12} width={70} text={`${offset.label} ${formatOffset(offset.measuredValue)}`} align="center" fontSize={12} fontStyle="bold" fill={mismatch?'#a4541e':'#553c7b'} padding={4}/></Group>}

function LinkedCanvasLabel({label}:{label:LinkedLabel}){const update=useSketchStore(s=>s.updateLinkedLabel);if(!label.visible)return null;return <Text x={label.position.x} y={label.position.y} text={label.text} rotation={label.orientation==='vertical'?-90:0} fontSize={14} fontStyle={label.type==='street-name'?'bold':'normal'} fill={label.type==='street-name'?'#263f5c':'#3d4b46'} padding={5} draggable onDragEnd={e=>update(label.id,{position:{x:e.target.x(),y:e.target.y()}})} />}

function MeasuredStructureShape({ structure }: { structure: MeasuredStructure }) {
  const selected = useSketchStore(s => s.selectedMeasuredId === structure.id); const select = useSketchStore(s => s.setSelectedMeasured);
  const session=useSketchStore(s=>s.builderSession),offsetSession=useSketchStore(s=>s.offsetSession),selectedSegmentId=useSketchStore(s=>s.selectedSegmentId),selectSegment=useSketchStore(s=>s.setSelectedSegment); const geometry = calculateStructure(structure); const points = geometry.points.flatMap(p => [p.x,p.y]); const newest=session?.status==='walking'&&session.structureId===structure.id?geometry.segments.at(-1):undefined;
  return <Group onClick={e=>{e.cancelBubble=true;select(structure.id)}} onTap={e=>{e.cancelBubble=true;select(structure.id)}}>
    <Line points={points} closed={structure.closed} stroke={structure.stroke} fill={structure.closed ? structure.fill : undefined} strokeWidth={structure.lineWidth} lineJoin="round" hitStrokeWidth={18}/>
    {newest&&<Line points={[newest.start.x,newest.start.y,newest.end.x,newest.end.y]} stroke="#e58b2f" strokeWidth={7} lineCap="round" shadowColor="#e58b2f" shadowBlur={8} opacity={.9} listening={false}/>} 
    {geometry.segments.map(({segment,start,end}) => <Group key={segment.id} onClick={e=>{e.cancelBubble=true;const os=useSketchStore.getState().offsetSession;if(os?.step==='first'||os?.step==='second')useSketchStore.getState().chooseOffsetFeature({kind:'structure-segment',objectId:structure.id,segmentId:segment.id,description:`${structure.name} wall ${segment.sequence}`});else selectSegment(structure.id,segment.id)}} onTap={e=>{e.cancelBubble=true;selectSegment(structure.id,segment.id)}}><Line points={[start.x,start.y,end.x,end.y]} stroke={selectedSegmentId===segment.id?'#e58b2f':'rgba(0,0,0,0)'} strokeWidth={selectedSegmentId===segment.id?8:18} opacity={selectedSegmentId===segment.id ? .9 : 1}/>{segment.visibleLabel&&<Text x={(start.x+end.x)/2-30} y={(start.y+end.y)/2-22} width={60} text={segment.label} align="center" fontSize={13} fontStyle="bold" fill="#173b32" padding={3} listening={false}/>}</Group>)}
    {selected && geometry.points.map((p,i)=><Circle key={i} x={p.x} y={p.y} radius={6} fill="#fff" stroke="#235e4e" strokeWidth={2}/>) }
    {(offsetSession?.step==='first'||offsetSession?.step==='second')&&geometry.points.map((p,i)=><Circle key={`offset-corner-${i}`} x={p.x} y={p.y} radius={8} fill="#fff4e7" stroke="#d97b27" strokeWidth={3} onClick={e=>{e.cancelBubble=true;useSketchStore.getState().chooseOffsetFeature({kind:'structure-corner',objectId:structure.id,segmentId:String(i),description:`${structure.name} corner ${i+1}`})}}/>)}
    <Text x={geometry.bounds.x} y={geometry.bounds.y-34} text={structure.name} fontSize={15} fontStyle="bold" fill="#173b32" listening={false}/>
  </Group>;
}

function CanvasObject({ object: o }: { object: SketchObject }) {
  const s = useSketchStore(); const selected = s.selectedIds.includes(o.id); const common = { id: o.id, x: o.x, y: o.y, rotation: o.rotation, draggable: !o.locked && s.activeTool === 'select'&&!s.offsetSession, onClick: (e: Konva.KonvaEventObject<MouseEvent>) => { e.cancelBubble = true;if(s.offsetSession?.step==='first'||s.offsetSession?.step==='second'){s.chooseOffsetFeature({kind:'sketch-object',objectId:o.id,description:o.name});return;} if (s.activeTool === 'delete') { s.setSelection([o.id]); s.deleteSelected(); return; } if (s.activeTool !== 'select') return; s.setSelection(e.evt.shiftKey ? (selected ? s.selectedIds.filter(id => id !== o.id) : [...s.selectedIds, o.id]) : [o.id]); }, onTap: (e: Konva.KonvaEventObject<TouchEvent>) => { e.cancelBubble = true; s.setSelection([o.id]); }, onDragStart: () => { if (!selected) s.setSelection([o.id]); }, onDragEnd: (e: Konva.KonvaEventObject<DragEvent>) => { const nx = s.canvas.snapToGrid ? snap(e.target.x(), s.canvas.gridSize) : e.target.x(), ny = s.canvas.snapToGrid ? snap(e.target.y(), s.canvas.gridSize) : e.target.y(); const dx = nx - o.x, dy = ny - o.y; const updates: Record<string, Partial<SketchObject>> = {}; (selected ? s.selectedIds : [o.id]).forEach(id => { const item = s.objects.find(x => x.id === id); if (item) updates[id] = { x: item.x + dx, y: item.y + dy }; }); s.updateObjects(updates); }, onTransformEnd: (e: Konva.KonvaEventObject<Event>) => { const n = e.target; const width = Math.max(12, o.width * n.scaleX()), height = Math.max(o.type === 'fence' ? 0 : 12, o.height * n.scaleY()); n.scaleX(1); n.scaleY(1); s.updateObject(o.id, { x: n.x(), y: n.y(), width: s.canvas.snapToGrid ? snap(width, s.canvas.gridSize) : width, height: s.canvas.snapToGrid ? snap(height, s.canvas.gridSize) : height, rotation: n.rotation() }); } };
  if (o.type === 'polygon') return <Group {...common}><Line points={scaleVertices(o.vertices, o.width, o.height)} closed fill={o.fill} stroke={o.stroke} strokeWidth={o.lineWidth}/><Text text={o.name} width={o.width} height={o.height} align="center" verticalAlign="middle" fontSize={14} fill="#334155" listening={false}/></Group>;
  if (o.type === 'fence') return <Group {...common}><Line points={[0,0,o.width,0]} stroke={o.stroke} strokeWidth={o.lineWidth} dash={[10,6]}/><Text text={o.name} y={-24} width={o.width} align="center" fontSize={13} fill="#475569" listening={false}/></Group>;
  return <Group {...common}><Rect width={o.width} height={o.height} fill={o.fill} stroke={o.stroke} strokeWidth={o.lineWidth} dash={o.type === 'lot' ? [12, 6] : undefined} cornerRadius={o.type === 'driveway' || o.type === 'sidewalk' ? 5 : 1}/>{o.type === 'house' && <Line points={[0,0,o.width/2,-24,o.width,0]} stroke={o.stroke} strokeWidth={o.lineWidth} fill={o.fill} closed/>}<Text text={o.name} width={o.width} height={o.height} align="center" verticalAlign="middle" fontSize={14} fill="#334155" listening={false}/></Group>;
}
const scaleVertices = (v: number[], w: number, h: number) => { const maxX = Math.max(...v.filter((_,i)=>i%2===0), 1), maxY = Math.max(...v.filter((_,i)=>i%2===1), 1); return v.map((n,i) => i%2===0 ? n/maxX*w : n/maxY*h); };
const selectedIdsLocked = (objects: SketchObject[], ids: string[]) => ids.some(id => objects.find(o => o.id === id)?.locked);
const isInput = (t: EventTarget | null) => t instanceof HTMLInputElement || t instanceof HTMLTextAreaElement;
const formatOffset = (value:number) => `${Number(value.toFixed(2))}'`;
